apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${namespace}pv
  labels:
    storetype: nfs
    itsmaService: deployer
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: ${NFS_SERVER} 
    path: "${NFS_OUTPUT_PATH}"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ${namespace}-vol-claim
  namespace: ${namespace}
  labels:
    itsmaService: deployer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: ${namespace}pv
